- type: entity
  id: BaseMindRole
  name: Mind Role
  description: Mind Role entity
  abstract: true
  components:
  - type: MindRole

- type: entity
  parent: BaseMindRole
  id: BaseMindRoleAntag
  abstract: true
  components:
  - type: MindRole
    antag: true

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleLoneAbductor
  name: Lone Abductor Role
  components:
  - type: MindRole
    exclusiveAntag: true
    antagPrototype: LoneAbductorAntag
  - type: Abductor

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleAbductorVictim
  name: Abductee Role
  components:
  - type: MindRole
    antagPrototype: AbductorVictimAntag
  - type: AbductorVictim

# goob edit - antags
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleChangeling
  name: Changeling Role
  components:
  - type: MindRole
    antagPrototype: Changeling
    exclusiveAntag: true
  - type: ChangelingRole
