- type: job
  id: Clerk
  name: job-name-clerk
  description: job-description-clerk
  playTimeTracker: JobClerk
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      min: 9000 # 2.5 hrs
    - !type:CharacterPlaytimeRequirement
      tracker: JobLawyer
      min: 9000 # 2.5 hrs
    - !type:CharacterPlaytimeRequirement
      tracker: JobProsecutor
      min: 9000 # 2.5 hrs


  startingGear: ClerkGear
  icon: "JobIconClerk"
  requireAdminNotify: true
  supervisors: job-supervisors-cj
  canBeAntag: false
  access:
  - Justice
  - Security
  - Maintenance

- type: startingGear
  id: ClerkGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitClerk
    back: ClothingBackpackFilled
    shoes: ClothingShoesBootsLaceup
    id: ClerkPDA
    ears: ClothingHeadsetJustice
  innerClothingSkirt: ClothingUniformJumpskirtClerk
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled


