# No idea why it's in sci but we ball.
- type: job
  id: StationAi
  name: job-name-station-ai
  description: job-description-station-ai
  playTimeTracker: JobStationAi
  requirements:
  - !type:CharacterOverallTimeRequirement
      min: 9900
  canBeAntag: false
  icon: JobIconStationAi
  supervisors: job-supervisors-rd
  jobEntity: StationAiBrain
  nameDataset: NamesAI
  spawnLoadout: false
  applyTraits: false
  alwaysUseSpawner: true

- type: job
  id: Borg
  name: job-name-borg
  description: job-description-borg
  playTimeTracker: JobBorg
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 8800
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-rd
  jobEntity: PlayerBorgGeneric

- type: job
  id: SecurityQuadBorg
  name: job-name-security-quadborg
  description: job-description-borg
  playTimeTracker: JobSecurityQuadBorg
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 8800
    - !type:DepartmentTimeRequirement
      department: Security
      min: 3600 #1 hrs floof
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-hos
  jobEntity: PlayerBorgQuadsec

- type: job
  id: SalvageQuadBorg
  name: job-name-salvage-quadborg
  description: job-description-borg
  playTimeTracker: JobSalvageQuadBorg
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 8800 #1 hr
    - !type:DepartmentTimeRequirement
      department: Logistics
      min: 3600 #1 hrs floof
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-qm
  jobEntity: PlayerBorgQuadsalvage
